### ISSUE TITLE
question about copyright

### ISSUE THREAD

**Issue by 0w0n2** [ademakdogan/nails_segmentation#1]
Hi, I'm a junior in university student. For a class project assignment, my teammates and I utilized your "nails_segmentation" project to create a nail color recommendation app. At a good opportunity, our professor offer us to help  register software. But we can't find any License mention in your posted files, so I send you this message. Can we register it? We have been used it for non-commercial purposes. Thank you.

**Comment by ademakdogan** [comment]
Certainly, you can use it 👍

**Comment by 0w0n2** [comment]
Thank you!! Have a nice day 👍
